package org.jdbscript.usecases;

import org.jdbscript.*;
import org.jdbscript.IDBSchema.IDBRecord;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Exercises the {@link JDBFeature.Group#DB2_ID_OWNED_SEQUENCE} feature group end to end against a
 * live DB2, where {@code afterInsert()} finds an identity-owned sequence it can't touch via
 * {@code ALTER SEQUENCE} (see {@link org.jdbscript.impl.sql.Db2Strategy}). {@link Db2StrategyTest}
 * (in impl.sql) already covers each branch with mocks; this proves the real SQL against real DB2.
 */
@Test
public class Db2FeatureTest extends JdbAbstractTest {

    private final static String TABLE_WITH_AUTO_ID = "generated_int_id_table";

    public interface ITableWithAutoGeneratedId extends IDBRecord {
        ITableWithAutoGeneratedId generated_id_column(Integer value);
        ITableWithAutoGeneratedId varchar_column(String value);
    }
    private interface IAutoGeneratedIdTestSchema extends IDBSchema {
        ITableWithAutoGeneratedId generated_int_id_table();
    }

    @BeforeMethod
    public void beforeMethod() {
        skipUnless("DB2_ID_OWNED_SEQUENCE_* feature", DBMSType.DB2);
        cleanupTables(TABLE_WITH_AUTO_ID);
    }

    private long readGeneratedId(String varcharColumnValue) {
        return withResultSet(
                "SELECT generated_id_column FROM %s WHERE varchar_column = '%s'"
                        .formatted(TABLE_WITH_AUTO_ID, varcharColumnValue),
                (rs, columns, types) -> {
                    assertThat(rs.next()).describedAs("row '%s' should exist", varcharColumnValue).isTrue();
                    return rs.getLong(1);
                });
    }

    @Test
    public void unconfigured_default_should_fail_clearly_instead_of_silently_leaving_the_identity_column_unreset() {
        // engineBuilder() sets DB2_ID_OWNED_SEQUENCE_RESTART_WITH for every other test in this
        // suite (see its javadoc) - this test deliberately builds without it, to prove the actual,
        // unconfigured default (DB2_ID_OWNED_SEQUENCE_ERROR) fails loudly rather than silently.
        IJDBEngine<IAutoGeneratedIdTestSchema> engine = JDBEngine.builder(IAutoGeneratedIdTestSchema.class)
                .dataSource(() -> dataSource)
                .executor(testConfiguration.getScriptExecutor())
                .cacheStrategy(CacheStrategy.GLOBAL)
                .build();

        assertThatThrownBy(() -> engine.insertDB(db ->
                db.generated_int_id_table().generated_id_column(1).varchar_column("manual")))
                .isInstanceOf(RuntimeException.class)
                .hasMessageContaining("GENERATED_INT_ID_TABLE")
                .hasMessageContaining("GENERATED_ID_COLUMN")
                .hasMessageContaining("JDBFeature");
    }

    @Test
    public void NOT_MODIFIED_feature_should_leave_the_identity_columns_counter_unaware_of_the_manual_insert() {
        IJDBEngine<IAutoGeneratedIdTestSchema> engine = engineBuilder(IAutoGeneratedIdTestSchema.class)
                .feature(JDBFeature.DB2_ID_OWNED_SEQUENCE_NOT_MODIFIED)
                .build();
        int manualId = 900_000_000;

        engine.insertDB(db -> db.generated_int_id_table().generated_id_column(manualId).varchar_column("manual"));
        // Bypasses the engine entirely, the same way a later, unrelated auto-generated insert would.
        executeUpdate("INSERT INTO %s (varchar_column) VALUES ('auto')", TABLE_WITH_AUTO_ID);

        long autoId = readGeneratedId("auto");
        assertThat(autoId)
                .describedAs("the identity column's counter was never told about the manual insert, "
                        + "so it kept incrementing from wherever it already was, nowhere near manualId")
                .isLessThan(manualId);
    }

    @Test
    public void RESTART_WITH_feature_should_reset_the_identity_column_so_a_later_auto_generated_id_cant_collide() {
        IJDBEngine<IAutoGeneratedIdTestSchema> engine = engineBuilder(IAutoGeneratedIdTestSchema.class)
                .feature(JDBFeature.DB2_ID_OWNED_SEQUENCE_RESTART_WITH)
                .build();

        engine.insertDB(db -> db.generated_int_id_table().generated_id_column(1).varchar_column("manual"));
        executeUpdate("INSERT INTO %s (varchar_column) VALUES ('auto')", TABLE_WITH_AUTO_ID);

        // RESTART WITH 10000 is absolute, not relative to whatever the counter held before -
        // deterministic regardless of what earlier tests in the suite did to this same counter.
        assertThat(readGeneratedId("auto")).isEqualTo(10000L);
    }
}
