package org.jdbscript.usecases;

import org.jdbscript.*;
import org.jdbscript.IDBSchema.IDBRecord;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

@Test
public class GeneratedIdTest extends JdbAbstractTest {

    private final static String TABLE_WITH_DEFAULTS = "table_with_defaults";
    private final static String TABLE_WITH_AUTO_ID = "generated_int_id_table";

    public interface ITableWithDefaultsRecord extends IDBRecord {
        ITableWithDefaultsRecord int_column_1(Integer value);
        ITableWithDefaultsRecord str_column_1(String value);
        default void defaults(RecordTools tools) {
            int_column_1(tools.nextIntId("id", 1));
            str_column_1("value");
        }
    }
    private interface IDefaultsTestSchema extends IDBSchema {

        ITableWithDefaultsRecord table_with_defaults();

    }


    public interface ITableWithAutoGeneratedId extends IDBRecord {
        ITableWithAutoGeneratedId generated_id_column(Integer value);
        ITableWithAutoGeneratedId varchar_column(String value);
        default void defaults(RecordTools tools) {
            int id = tools.nextIntId("id", 1);
            generated_id_column(id);
            varchar_column("text"+id);
        }
    }
    private interface IAutoGeneratedIdTestSchema extends IDBSchema {

        ITableWithAutoGeneratedId generated_int_id_table();

    }

    @BeforeMethod
    public void beforeMethod(){
        cleanupTables(TABLE_WITH_DEFAULTS);
    }

    private final JDBEngine<IDefaultsTestSchema> engine = createEngine(IDefaultsTestSchema.class);
    private final JDBEngine<IAutoGeneratedIdTestSchema> autoIdEngine = createEngine(IAutoGeneratedIdTestSchema.class);

    @Test
    public void nextInt_in_defaults_should_increment_each_successive_returned_value() {
        engine.resetDB((db)->{
            db.table_with_defaults();
            db.table_with_defaults();
            db.table_with_defaults();
            db.table_with_defaults();
            db.table_with_defaults();
        });

        assertTableValues(table(TABLE_WITH_DEFAULTS,
                columns("str_column_1", "int_column_1"),
                row("value", 1),
                row("value", 2),
                row("value", 3),
                row("value", 4),
                row("value", 5)
        ));
    }

    private static abstract class AutoGeneratedIds implements IDefaultsTestSchema {{
        table_with_defaults();
        table_with_defaults();
    }}

    @Test(dependsOnMethods = "nextInt_in_defaults_should_increment_each_successive_returned_value")
    public void inserted_ids_should_support_include_of_script_with_same_id_column() {
        engine.resetDB((db)->{
            db.include(AutoGeneratedIds.class);
            db.table_with_defaults();
            db.table_with_defaults();
            db.table_with_defaults();
        });


        assertTableValues(table(TABLE_WITH_DEFAULTS,
                columns("str_column_1", "int_column_1"),
                row("value", 1),
                row("value", 2),
                row("value", 3),
                row("value", 4),
                row("value", 5)
        ));
    }

    @Test(dependsOnMethods = "nextInt_in_defaults_should_increment_each_successive_returned_value")
    public void inserted_ids_should_not_break_dbs_autogenerated_ids() {
        autoIdEngine.resetDB((db)->{
            db.generated_int_id_table();
            db.generated_int_id_table();
            db.generated_int_id_table();
            db.generated_int_id_table();
            db.generated_int_id_table();
        });

        executeUpdate("INSERT INTO %s (varchar_column) VALUES ('inserted1')", TABLE_WITH_AUTO_ID);
        executeUpdate("INSERT INTO %s (varchar_column) VALUES ('inserted2')", TABLE_WITH_AUTO_ID);

        assertTableValues(table(TABLE_WITH_AUTO_ID, "varchar_column like 'inserted%'",
                columns( "varchar_column"),
                row( "inserted1"),
                row( "inserted2")
        ));
        assertTableValues(table(TABLE_WITH_AUTO_ID, "varchar_column like 'text%'",
                columns("generated_id_column", "varchar_column"),
                row( 1, "text1"),
                row( 2, "text2"),
                row( 3, "text3"),
                row( 4, "text4"),
                row( 5, "text5")
        ));
    }
}
